# ============================================================
# hosts/desktop/configuration.nix
# ============================================================

{ config, pkgs, inputs, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config
    ../../modules/base-config.nix  # shared settings (locale, fonts, etc.)
    ../../modules/kde-base.nix
    ../../modules/apps.nix         # GUI & CLI applications
    ../../modules/shell.nix        # zsh, aliases, environment
    ../../modules/git.nix          # git + GitHub tooling
    ../../modules/development.nix
    # NOTE: ../../home/default.nix is no longer imported here.
    # The flake passes it as a NixOS module directly, which is the
    # correct way to wire home-manager when using flakes.
  ];

  home-manager.sharedModules = [
    inputs.plasma-manager.homeModules.plasma-manager
    inputs.zen-browser.homeModules.beta
  ];

  home-manager.users.nixos = {
    imports = [
        ../../modules/user/kde-config.nix
    ];
  };

  # ── Machine identity ────────────────────────────────────────
  networking.hostName = "nixos-desktop";

  # ── Boot ────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Use latest kernel.
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.luks.devices."luks-a7524fbc-845c-49f8-9d07-428ea61e4a1c".device = "/dev/disk/by-uuid/a7524fbc-845c-49f8-9d07-428ea61e4a1c";

  # ── Hardware ────────────────────────────────────────────────
  # Uncomment ONE of the following GPU blocks:

  # --- NVIDIA ---
  #services.xserver.videoDrivers = [ "nvidia" ];
  #hardware.nvidia.modesetting.enable = true;
  #hardware.nvidia.open = false;
  #hardware.graphics.enable = true;

  # ── CPU microcode ───────────────────────────────────────────
  hardware.cpu.amd.updateMicrocode = true;

  # ── Bluetooth ───────────────────────────────────────────────
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # ── Sound (PipeWire) ────────────────────────────────────────
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ── User account ────────────────────────────────────────────
  users.users.nixos = {   # TO_CHANGE
    isNormalUser = true;
    description = "Nix OS";   # TO_CHANGE
    extraGroups = [ "wheel" "networkmanager" "audio" "video" ];
    shell = pkgs.zsh;
  };

  nixpkgs.config.permittedInsecurePackages = [
    "openssl-1.1.1w"
  ];

  # ── This value pins the NixOS version for stateful options.
  # Do NOT change this after first install.
  system.stateVersion = "25.11";
}
