# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-52925e55-c630-477e-98e0-90e1ca3dea2b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-52925e55-c630-477e-98e0-90e1ca3dea2b".device = "/dev/disk/by-uuid/52925e55-c630-477e-98e0-90e1ca3dea2b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/43C8-B68F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-a7524fbc-845c-49f8-9d07-428ea61e4a1c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
